[package]
name = "state_view"
version = "0.1.0"
authors = ["XPeer Association <opensource@xpeer.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
failure = { path = "../../common/failure_ext", package = "failure_ext" }
types = { path = "../../types" }