[package]
name = "vm_cache_map"
version = "0.1.0"
authors = ["XPeer Association <opensource@xpeer.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
chashmap = "2.2.2"
typed-arena = "1.4.1"

[dev-dependencies]
crossbeam = "0.7"
proptest = "0.9"
rand = "0.6"
